version : "1.0"

services:
  sandbox-backend:
    image: sandbox-backend-image
    container_name: sandbox-backend-container
    build: .
    env_file:
      - "/etc/node-env/sandbox-backend.com/.env"
    environment:
      NODE_ENV: production
    ports:
      - "6001:6001"
    volumes:
      - /etc/node-env/sandbox-backend.com/.env:/app/.env
    restart: always
